spring.application.name=clubs-backend
spring.datasource.url=jdbc:mysql://localhost:3306/college_clubs
spring.datasource.username=root
spring.datasource.password=ankita123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080